# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QTableWidget, QTableWidgetItem, QTextEdit, QWidget)
import icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1128, 539)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(30, 20, 101, 61))
        icon = QIcon()
        icon.addFile(u"icons/today.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QSize(60, 60))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(30, 100, 101, 61))
        icon1 = QIcon()
        icon1.addFile(u"icons/book.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QSize(60, 60))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(30, 260, 101, 61))
        icon2 = QIcon()
        icon2.addFile(u"icons/user.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QSize(60, 60))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(30, 340, 101, 61))
        icon3 = QIcon()
        icon3.addFile(u"icons/settings.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QSize(60, 60))
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(30, 420, 101, 61))
        icon4 = QIcon()
        icon4.addFile(u"icons/theme.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QSize(60, 60))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(160, 10, 961, 491))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tableWidget = QTableWidget(self.tab)
        if (self.tableWidget.columnCount() < 5):
            self.tableWidget.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(0, 100, 961, 311))
        self.pushButton_6 = QPushButton(self.tab)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(800, 30, 121, 41))
        self.lineEdit = QLineEdit(self.tab)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(20, 30, 181, 31))
        self.lineEdit.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.comboBox = QComboBox(self.tab)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(500, 40, 91, 22))
        self.comboBox_2 = QComboBox(self.tab)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(670, 40, 69, 22))
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(430, 40, 61, 21))
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(610, 40, 51, 20))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.lineEdit_29 = QLineEdit(self.tab)
        self.lineEdit_29.setObjectName(u"lineEdit_29")
        self.lineEdit_29.setGeometry(QRect(220, 30, 181, 31))
        self.lineEdit_29.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.pushButton_29 = QPushButton(self.tab)
        self.pushButton_29.setObjectName(u"pushButton_29")
        self.pushButton_29.setGeometry(QRect(650, 420, 281, 31))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget_2 = QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 0, 961, 461))
        self.tabWidget_2.setTabPosition(QTabWidget.North)
        self.tabWidget_2.setTabShape(QTabWidget.Rounded)
        self.tabWidget_2.setElideMode(Qt.ElideNone)
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.tableWidget_6 = QTableWidget(self.tab_10)
        if (self.tableWidget_6.columnCount() < 7):
            self.tableWidget_6.setColumnCount(7)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(5, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(6, __qtablewidgetitem11)
        self.tableWidget_6.setObjectName(u"tableWidget_6")
        self.tableWidget_6.setGeometry(QRect(0, 0, 951, 381))
        self.pushButton_27 = QPushButton(self.tab_10)
        self.pushButton_27.setObjectName(u"pushButton_27")
        self.pushButton_27.setGeometry(QRect(730, 390, 201, 31))
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.lineEdit_2 = QLineEdit(self.tab_5)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(190, 50, 221, 41))
        self.lineEdit_5 = QLineEdit(self.tab_5)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(650, 70, 251, 41))
        self.comboBox_5 = QComboBox(self.tab_5)
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.comboBox_5.setGeometry(QRect(650, 131, 251, 31))
        self.lineEdit_6 = QLineEdit(self.tab_5)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(650, 280, 251, 41))
        self.pushButton_7 = QPushButton(self.tab_5)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(410, 370, 151, 41))
        self.label_3 = QLabel(self.tab_5)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 50, 81, 31))
        self.label_4 = QLabel(self.tab_5)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(530, 70, 81, 31))
        self.comboBox_6 = QComboBox(self.tab_5)
        self.comboBox_6.setObjectName(u"comboBox_6")
        self.comboBox_6.setGeometry(QRect(650, 180, 251, 31))
        self.comboBox_7 = QComboBox(self.tab_5)
        self.comboBox_7.setObjectName(u"comboBox_7")
        self.comboBox_7.setGeometry(QRect(650, 230, 251, 31))
        self.label_5 = QLabel(self.tab_5)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(530, 290, 81, 31))
        self.label_6 = QLabel(self.tab_5)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(530, 130, 81, 31))
        self.label_7 = QLabel(self.tab_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(530, 180, 81, 31))
        self.label_8 = QLabel(self.tab_5)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(530, 230, 81, 31))
        self.textEdit = QTextEdit(self.tab_5)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(30, 110, 381, 231))
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.comboBox_8 = QComboBox(self.tab_6)
        self.comboBox_8.setObjectName(u"comboBox_8")
        self.comboBox_8.setGeometry(QRect(650, 151, 251, 31))
        self.label_9 = QLabel(self.tab_6)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(530, 150, 81, 31))
        self.lineEdit_7 = QLineEdit(self.tab_6)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(650, 300, 251, 41))
        self.label_10 = QLabel(self.tab_6)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(530, 90, 81, 31))
        self.label_11 = QLabel(self.tab_6)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(530, 200, 81, 31))
        self.lineEdit_9 = QLineEdit(self.tab_6)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(650, 90, 251, 41))
        self.label_12 = QLabel(self.tab_6)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(530, 250, 81, 31))
        self.label_13 = QLabel(self.tab_6)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(530, 310, 81, 31))
        self.label_14 = QLabel(self.tab_6)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(100, 20, 81, 31))
        self.lineEdit_3 = QLineEdit(self.tab_6)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(220, 20, 221, 41))
        self.comboBox_9 = QComboBox(self.tab_6)
        self.comboBox_9.setObjectName(u"comboBox_9")
        self.comboBox_9.setGeometry(QRect(650, 200, 251, 31))
        self.comboBox_10 = QComboBox(self.tab_6)
        self.comboBox_10.setObjectName(u"comboBox_10")
        self.comboBox_10.setGeometry(QRect(650, 250, 251, 31))
        self.pushButton_8 = QPushButton(self.tab_6)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(410, 370, 151, 41))
        self.label_15 = QLabel(self.tab_6)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(60, 90, 81, 31))
        self.lineEdit_10 = QLineEdit(self.tab_6)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(180, 90, 221, 41))
        self.pushButton_9 = QPushButton(self.tab_6)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(520, 20, 191, 31))
        self.pushButton_10 = QPushButton(self.tab_6)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(80, 370, 151, 41))
        self.textEdit_2 = QTextEdit(self.tab_6)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(40, 140, 381, 201))
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.tabWidget_4 = QTabWidget(self.tab_11)
        self.tabWidget_4.setObjectName(u"tabWidget_4")
        self.tabWidget_4.setGeometry(QRect(0, 0, 961, 461))
        self.tabWidget_4.setTabPosition(QTabWidget.North)
        self.tabWidget_4.setTabShape(QTabWidget.Rounded)
        self.tabWidget_4.setElideMode(Qt.ElideNone)
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.tableWidget_5 = QTableWidget(self.tab_12)
        if (self.tableWidget_5.columnCount() < 3):
            self.tableWidget_5.setColumnCount(3)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, __qtablewidgetitem14)
        self.tableWidget_5.setObjectName(u"tableWidget_5")
        self.tableWidget_5.setGeometry(QRect(0, 0, 951, 381))
        self.pushButton_28 = QPushButton(self.tab_12)
        self.pushButton_28.setObjectName(u"pushButton_28")
        self.pushButton_28.setGeometry(QRect(720, 390, 211, 31))
        self.tabWidget_4.addTab(self.tab_12, "")
        self.tab_13 = QWidget()
        self.tab_13.setObjectName(u"tab_13")
        self.lineEdit_4 = QLineEdit(self.tab_13)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(380, 90, 291, 41))
        self.pushButton_17 = QPushButton(self.tab_13)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(410, 370, 151, 41))
        self.label_31 = QLabel(self.tab_13)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(240, 90, 91, 31))
        self.lineEdit_8 = QLineEdit(self.tab_13)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(380, 160, 291, 41))
        self.label_32 = QLabel(self.tab_13)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(240, 160, 81, 31))
        self.lineEdit_24 = QLineEdit(self.tab_13)
        self.lineEdit_24.setObjectName(u"lineEdit_24")
        self.lineEdit_24.setGeometry(QRect(380, 230, 291, 41))
        self.label_33 = QLabel(self.tab_13)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(200, 230, 161, 31))
        self.tabWidget_4.addTab(self.tab_13, "")
        self.tab_14 = QWidget()
        self.tab_14.setObjectName(u"tab_14")
        self.label_42 = QLabel(self.tab_14)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(40, 20, 161, 31))
        self.lineEdit_27 = QLineEdit(self.tab_14)
        self.lineEdit_27.setObjectName(u"lineEdit_27")
        self.lineEdit_27.setGeometry(QRect(220, 20, 261, 41))
        self.pushButton_23 = QPushButton(self.tab_14)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.pushButton_23.setGeometry(QRect(560, 360, 151, 41))
        self.pushButton_24 = QPushButton(self.tab_14)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.pushButton_24.setGeometry(QRect(520, 30, 191, 31))
        self.pushButton_25 = QPushButton(self.tab_14)
        self.pushButton_25.setObjectName(u"pushButton_25")
        self.pushButton_25.setGeometry(QRect(230, 360, 151, 41))
        self.lineEdit_25 = QLineEdit(self.tab_14)
        self.lineEdit_25.setObjectName(u"lineEdit_25")
        self.lineEdit_25.setGeometry(QRect(330, 120, 291, 41))
        self.label_34 = QLabel(self.tab_14)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(190, 190, 81, 31))
        self.label_35 = QLabel(self.tab_14)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(190, 120, 91, 31))
        self.lineEdit_26 = QLineEdit(self.tab_14)
        self.lineEdit_26.setObjectName(u"lineEdit_26")
        self.lineEdit_26.setGeometry(QRect(330, 190, 291, 41))
        self.label_36 = QLabel(self.tab_14)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(150, 260, 161, 31))
        self.lineEdit_28 = QLineEdit(self.tab_14)
        self.lineEdit_28.setObjectName(u"lineEdit_28")
        self.lineEdit_28.setGeometry(QRect(330, 260, 291, 41))
        self.tabWidget_4.addTab(self.tab_14, "")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.groupBox = QGroupBox(self.tab_3)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 10, 441, 441))
        self.label_16 = QLabel(self.groupBox)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 70, 111, 41))
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 170, 121, 41))
        self.label_18 = QLabel(self.groupBox)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(20, 210, 131, 51))
        self.label_19 = QLabel(self.groupBox)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 120, 111, 41))
        self.lineEdit_11 = QLineEdit(self.groupBox)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(160, 70, 241, 41))
        self.lineEdit_12 = QLineEdit(self.groupBox)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(160, 120, 241, 41))
        self.lineEdit_13 = QLineEdit(self.groupBox)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(160, 170, 241, 41))
        self.lineEdit_13.setEchoMode(QLineEdit.Password)
        self.lineEdit_14 = QLineEdit(self.groupBox)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(160, 220, 241, 41))
        self.lineEdit_14.setEchoMode(QLineEdit.Password)
        self.pushButton_11 = QPushButton(self.groupBox)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(100, 340, 221, 41))
        self.label_30 = QLabel(self.groupBox)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(100, 280, 301, 21))
        self.groupBox_2 = QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(480, 10, 461, 171))
        self.lineEdit_17 = QLineEdit(self.groupBox_2)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(170, 30, 241, 41))
        self.label_21 = QLabel(self.groupBox_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(30, 30, 111, 41))
        self.lineEdit_15 = QLineEdit(self.groupBox_2)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(170, 80, 241, 41))
        self.lineEdit_15.setEchoMode(QLineEdit.Password)
        self.label_22 = QLabel(self.groupBox_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(30, 80, 121, 41))
        self.pushButton_12 = QPushButton(self.groupBox_2)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(180, 130, 211, 31))
        self.groupBox_4 = QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setGeometry(QRect(480, 180, 461, 271))
        self.label_23 = QLabel(self.groupBox_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(30, 30, 111, 41))
        self.lineEdit_20 = QLineEdit(self.groupBox_4)
        self.lineEdit_20.setObjectName(u"lineEdit_20")
        self.lineEdit_20.setGeometry(QRect(170, 30, 241, 41))
        self.lineEdit_16 = QLineEdit(self.groupBox_4)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(170, 130, 241, 41))
        self.lineEdit_16.setEchoMode(QLineEdit.Password)
        self.label_24 = QLabel(self.groupBox_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(30, 170, 131, 51))
        self.lineEdit_18 = QLineEdit(self.groupBox_4)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(170, 180, 241, 41))
        self.lineEdit_18.setEchoMode(QLineEdit.Password)
        self.lineEdit_19 = QLineEdit(self.groupBox_4)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(170, 80, 241, 41))
        self.label_25 = QLabel(self.groupBox_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(30, 130, 121, 41))
        self.pushButton_13 = QPushButton(self.groupBox_4)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(120, 230, 221, 31))
        self.label_20 = QLabel(self.groupBox_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(30, 80, 111, 41))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tabWidget_3 = QTabWidget(self.tab_4)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(0, 0, 961, 461))
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.tableWidget_2 = QTableWidget(self.tab_7)
        if (self.tableWidget_2.columnCount() < 1):
            self.tableWidget_2.setColumnCount(1)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, __qtablewidgetitem15)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(0, 110, 951, 321))
        font1 = QFont()
        font1.setPointSize(11)
        self.tableWidget_2.setFont(font1)
        self.label_26 = QLabel(self.tab_7)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(80, 40, 181, 31))
        font2 = QFont()
        font2.setPointSize(13)
        self.label_26.setFont(font2)
        self.pushButton_14 = QPushButton(self.tab_7)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(580, 40, 151, 31))
        self.lineEdit_21 = QLineEdit(self.tab_7)
        self.lineEdit_21.setObjectName(u"lineEdit_21")
        self.lineEdit_21.setGeometry(QRect(270, 40, 241, 41))
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.tableWidget_3 = QTableWidget(self.tab_8)
        if (self.tableWidget_3.columnCount() < 1):
            self.tableWidget_3.setColumnCount(1)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, __qtablewidgetitem16)
        self.tableWidget_3.setObjectName(u"tableWidget_3")
        self.tableWidget_3.setGeometry(QRect(0, 110, 951, 321))
        self.tableWidget_3.setFont(font1)
        self.pushButton_15 = QPushButton(self.tab_8)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(580, 40, 151, 31))
        self.lineEdit_22 = QLineEdit(self.tab_8)
        self.lineEdit_22.setObjectName(u"lineEdit_22")
        self.lineEdit_22.setGeometry(QRect(270, 40, 241, 41))
        self.label_27 = QLabel(self.tab_8)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(80, 40, 181, 31))
        self.label_27.setFont(font2)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.tableWidget_4 = QTableWidget(self.tab_9)
        if (self.tableWidget_4.columnCount() < 1):
            self.tableWidget_4.setColumnCount(1)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, __qtablewidgetitem17)
        self.tableWidget_4.setObjectName(u"tableWidget_4")
        self.tableWidget_4.setGeometry(QRect(0, 110, 951, 321))
        self.tableWidget_4.setFont(font1)
        self.pushButton_16 = QPushButton(self.tab_9)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(580, 40, 151, 31))
        self.lineEdit_23 = QLineEdit(self.tab_9)
        self.lineEdit_23.setObjectName(u"lineEdit_23")
        self.lineEdit_23.setGeometry(QRect(270, 40, 241, 41))
        self.label_28 = QLabel(self.tab_9)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(80, 40, 181, 31))
        self.label_28.setFont(font2)
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tabWidget.addTab(self.tab_4, "")
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QRect(780, 0, 351, 501))
        self.groupBox_3.setStyleSheet(u"background-color: rgb(180, 180, 180);")
        self.label_29 = QLabel(self.groupBox_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(100, 70, 181, 41))
        font3 = QFont()
        font3.setFamilies([u"Segoe UI"])
        font3.setPointSize(16)
        self.label_29.setFont(font3)
        self.pushButton_21 = QPushButton(self.groupBox_3)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(0, 250, 31, 31))
        self.pushButton_18 = QPushButton(self.groupBox_3)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(190, 180, 121, 81))
        self.pushButton_19 = QPushButton(self.groupBox_3)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(60, 180, 121, 81))
        self.pushButton_20 = QPushButton(self.groupBox_3)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setGeometry(QRect(60, 270, 121, 81))
        self.pushButton_22 = QPushButton(self.groupBox_3)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(190, 270, 121, 81))
        self.pushButton_26 = QPushButton(self.centralwidget)
        self.pushButton_26.setObjectName(u"pushButton_26")
        self.pushButton_26.setGeometry(QRect(30, 180, 101, 61))
        icon5 = QIcon()
        icon5.addFile(u"icons/users.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_26.setIcon(icon5)
        self.pushButton_26.setIconSize(QSize(60, 60))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1128, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton.setText("")
        self.pushButton_2.setText("")
        self.pushButton_3.setText("")
        self.pushButton_4.setText("")
        self.pushButton_5.setText("")
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Book Name", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Client Name", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Type", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"From", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"To", None));
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter Book Title", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Retrieve", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Rent", None))

        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_2.setItemText(4, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_2.setItemText(5, QCoreApplication.translate("MainWindow", u"6", None))
        self.comboBox_2.setItemText(6, QCoreApplication.translate("MainWindow", u"7", None))
        self.comboBox_2.setItemText(7, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_2.setItemText(8, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_2.setItemText(9, QCoreApplication.translate("MainWindow", u"10", None))

        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">Type</span></p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">Days</span></p></body></html>", None))
        self.lineEdit_29.setInputMask("")
        self.lineEdit_29.setText("")
        self.lineEdit_29.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter Client Name", None))
        self.pushButton_29.setText(QCoreApplication.translate("MainWindow", u"Export Today Operations to Excel File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Tab 1", None))
        ___qtablewidgetitem5 = self.tableWidget_6.horizontalHeaderItem(0)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Book Code", None));
        ___qtablewidgetitem6 = self.tableWidget_6.horizontalHeaderItem(1)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Book Title", None));
        ___qtablewidgetitem7 = self.tableWidget_6.horizontalHeaderItem(2)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Book Description", None));
        ___qtablewidgetitem8 = self.tableWidget_6.horizontalHeaderItem(3)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Book Category", None));
        ___qtablewidgetitem9 = self.tableWidget_6.horizontalHeaderItem(4)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem10 = self.tableWidget_6.horizontalHeaderItem(5)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Book Author", None));
        ___qtablewidgetitem11 = self.tableWidget_6.horizontalHeaderItem(6)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Book Price", None));
        self.pushButton_27.setText(QCoreApplication.translate("MainWindow", u"Export Books to Excel File", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), QCoreApplication.translate("MainWindow", u"All Books", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Book Title", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Book Code", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Book Price", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Category", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Author", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Category", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Add New Book", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Category", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Book Code", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Author", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Category", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Book Price", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Book Title", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Book Title", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Edit / Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Tab 2", None))
        ___qtablewidgetitem12 = self.tableWidget_5.horizontalHeaderItem(0)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Client Name", None));
        ___qtablewidgetitem13 = self.tableWidget_5.horizontalHeaderItem(1)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Client Email", None));
        ___qtablewidgetitem14 = self.tableWidget_5.horizontalHeaderItem(2)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"Client Passport Number", None));
        self.pushButton_28.setText(QCoreApplication.translate("MainWindow", u"Export Clients to Excel File", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), QCoreApplication.translate("MainWindow", u"All Clients", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"Add New Client", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Client Name", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Client Email", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"ClientPassport Number", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), QCoreApplication.translate("MainWindow", u"Add New Client", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Client Passport Number", None))
        self.pushButton_23.setText(QCoreApplication.translate("MainWindow", u"Edit Client", None))
        self.pushButton_24.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.pushButton_25.setText(QCoreApplication.translate("MainWindow", u"Delete Client", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Client Email", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Client Name", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Client Passport Number", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_14), QCoreApplication.translate("MainWindow", u"Edit / Delete Client", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), QCoreApplication.translate("MainWindow", u"Page", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Add New User", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Username", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Password Again", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Email", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"Add User", None))
        self.label_30.setText("")
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Edit User Information", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Username", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"Login", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Edit User Data", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Username", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Password Again", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"Edit User Data", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Email", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Page", None))
        ___qtablewidgetitem15 = self.tableWidget_2.horizontalHeaderItem(0)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"Category Name", None));
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"New Category Name", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"Add New Category", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Categories", None))
        ___qtablewidgetitem16 = self.tableWidget_3.horizontalHeaderItem(0)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"Author Name", None));
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"Add New Author", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"New Author Name", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"Author", None))
        ___qtablewidgetitem17 = self.tableWidget_4.horizontalHeaderItem(0)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"Publisher Name", None));
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"New Publisher Name", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"New Publisher Name", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), QCoreApplication.translate("MainWindow", u"Publisher", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Page", None))
        self.groupBox_3.setTitle("")
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Apply New Theme", None))
        self.pushButton_21.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.pushButton_18.setText(QCoreApplication.translate("MainWindow", u"Dark Grey", None))
        self.pushButton_19.setText(QCoreApplication.translate("MainWindow", u"Dark Blue", None))
        self.pushButton_20.setText(QCoreApplication.translate("MainWindow", u"Classic", None))
        self.pushButton_22.setText(QCoreApplication.translate("MainWindow", u"Dark Orange", None))
        self.pushButton_26.setText("")
    # retranslateUi

